services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: dev
    ports:
      - "50051:50051"
    volumes:
      - ./backend:/work
    env_file:
      - ./backend/.env
