services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: deploy
    ports:
      - "50051:50051"
    volumes:
      - ./backend:/work/backend
      - ./proto:/work/proto
    env_file:
      - ./backend/.env
