services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: deploy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: deploy
