services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: dev
    ports:
      - "50051:50051"
    volumes:
      - ./backend:/work/backend
      - ./proto:/work/proto
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/work/frontend
      - ./proto:/work/proto
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
