FROM node:20-alpine AS base
WORKDIR /work/frontend

# Copy package files
COPY frontend/package*.json ./
COPY frontend /work/frontend
COPY proto /work/proto


FROM base AS dev
WORKDIR /work/frontend

# Install dependencies
COPY --from=base /work /work
# Set the buf registry
RUN npm install

CMD ["npm", "run", "dev"]


FROM base AS deploy
WORKDIR /work/frontend

COPY --from=base /work /work
# Set the buf registry
RUN npm install

CMD ["npm", "run", "build"]
