[workspace]
members = ["app", "crates/infra/app-server"]
resolver = "3"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
app-server = { path = "crates/infra/app-server" }

anyhow = "1.0.96"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "net"] }
