[package]
edition = "2024"
name = "app-server"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
axum = "0.8.1"
dotenv = "0.15.0"
env_logger = "0.11.6"
log = "0.4.26"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
