[package]
edition = "2024"
name = "app"
version = "0.1.0"
build = "build.rs"

[dependencies]
app-server = { path = "../crates/infra/app-server" }
anyhow = { workspace = true }
dotenv = "0.15.0"
env_logger = "0.11.6"
log = "0.4.26"
